name: Build Release

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
  push:
    tags:
      - 'v*'

jobs:
  create_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Create gdlauncher zip
        uses: papeloto/action-zip@v1
        with:
          files: overrides/ manifest.json
          recursive: false
          dest: gdlauncher-config.zip
      - name: Create update zip
        uses: papeloto/action-zip@v1
        with:
          files: overrides/config/
          dest: instance-update.zip
      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/*.zip




