name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Create gdlauncher zip
        uses: papeloto/action-zip@v1
        with:
          files: overrides/ manifest.json
          recursive: false
          dest: gdlauncher-config.zip
      - name: Create update zip
        uses: papeloto/action-zip@v1
        with:
          files: overrides/config/
          dest: instance-update.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/*.zip
          body_path: install-guide.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: Valastiri/the-rat-pack



